include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - example/**
    - src/**
    - ios/_setup/**
    - macos/_setup/**
    - android/_install/**
    - linux/_install/**
