name: build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-ios:
    strategy:
      matrix:
        name:
          - ios
    name: Build on iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          architecture: x64
      - name: Build
        working-directory: ./example
        run: |
          cp lib/environment.example.dart lib/environment.dart
          flutter pub get
          flutter config --enable-ios
          flutter build ios --release --no-codesign

  build-windows:
    strategy:
      matrix:
        name:
          - windows_x86_64
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Build
        working-directory: ./example
        run: |
          cp lib/environment.example.dart lib/environment.dart
          flutter pub get
          flutter config --enable-windows-desktop
          flutter build windows --release