name: build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-ios:
    strategy:
      matrix:
        name:
          - ios
    name: Build on iOS
    runs-on: macos-12
    env:
      XCODE: /Applications/Xcode_14.0.1.app
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode Version
        run: sudo xcode-select -s '${{ env.XCODE }}/Contents/Developer'
      - name: Show Xcode Version
        run: xcodebuild -version
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          architecture: x64
      - name: Build
        working-directory: ./example
        run: |
          cp lib/environment.example.dart lib/environment.dart
          flutter pub get
          flutter config --enable-ios
          flutter build ios --release --no-codesign

  build-android:
    strategy:
      matrix:
        name:
          - android
    name: Build on Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          architecture: x64
      - name: Configure Build
        working-directory: ./example
        run: |
          cp lib/environment.example.dart lib/environment.dart
          flutter pub get
          flutter config --enable-android
      - name: Build APK
        working-directory: ./example
          flutter build apk
      - name: Build App Bundle
        working-directory: ./example
          flutter build appbundle

  build-windows:
    strategy:
      matrix:
        name:
          - windows_x86_64
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Build
        working-directory: ./example
        run: |
          cp lib/environment.example.dart lib/environment.dart
          flutter pub get
          flutter config --enable-windows-desktop
          flutter build windows --release

  build-ubuntu:
    strategy:
      matrix:
        name:
          - ubuntu_x86_64
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libva-dev libdrm-dev
      - name: Build
        working-directory: ./example
        run: |
          cp lib/environment.example.dart lib/environment.dart
          flutter pub get
          flutter config --enable-linux-desktop
          ./linux/flutter/ephemeral/.plugin_symlinks/sora_flutter_sdk/linux/install_deps.sh linux/
          export PATH="`pwd`/linux/_install/llvm/clang/bin:$PATH"
          flutter build linux --release