name: test

on:
  push:
    paths-ignore:
      - '.github/workflows/build.yaml'
      - '**.md'
      - 'example'
      - '.fvm'

jobs:
  test:
    strategy:
      matrix:
        target:
          - ios
          # Sora C++ SDK は x86_64 に非対応
          # - macos
    name: Test on ${{ matrix.target }}
    runs-on: macos-12
    env:
      XCODE: /Applications/Xcode_14.0.1.app
      SIGNALING_URL1: ${{ secrets.TEST_SIGNALING_URL1 }}
      SIGNALING_URL2: ${{ secrets.TEST_SIGNALING_URL2 }}
      SIGNALING_URL3: ${{ secrets.TEST_SIGNALING_URL3 }}
      CHANNEL_ID: ${{ secrets.TEST_CHANNEL_ID }}
      METADATA: ${{ secrets.TEST_METADATA }}
    steps:
      - name: Add Masked Secrets
        run: |
          echo "::add-mask::$SIGNALING_URL1"
          echo "::add-mask::$SIGNALING_URL2"
          echo "::add-mask::$SIGNALING_URL3"
          echo "::add-mask::$CHANNEL_ID"
          echo "::add-mask::$METADATA"
      - name: Create Test Channel ID
        run: |
          uuidgen > USER.txt
          echo "::add-mask::`cat USER.txt`"
          echo "::add-mask::`cat USER.txt`@$CHANNEL_ID"
          echo "CHANNEL_ID=`cat USER.txt`@$CHANNEL_ID" >> $GITHUB_ENV
          rm USER.txt
      - uses: actions/checkout@v3
      - name: Select Xcode Version
        run: sudo xcode-select -s '${{ env.XCODE }}/Contents/Developer'
      - name: Show Xcode Version
        run: xcodebuild -version
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          architecture: x64
      - name: Show Flutter Available Emulators
        if: matrix.target == 'ios'
        run: flutter emulators
      - name: Launch iOS Simulator
        if: matrix.target == 'ios'
        run: flutter emulators --launch apple_ios_simulator
      - name: Show Flutter Available Devices
        if: matrix.target == 'ios'
        run: flutter devices
      - name: Generate Configuration
        working-directory: ./integration_test_app
        run: ../scripts/create_env.sh lib/environment.dart "$SIGNALING_URL1,$SIGNALING_URL2,$SIGNALING_URL3" "${{ env.CHANNEL_ID }}" "$METADATA"
      - name: Get Flutter Dependencies
        working-directory: ./integration_test_app
        run: flutter pub get
      - name: Run Integration Tests
        working-directory: ./integration_test_app
        run: |
          if [ "${{ matrix.target }}" = "ios" ]; then
            flutter test integration_test/connect_test.dart -d iPhone
          else
            flutter test integration_test/connect_test.dart -d macos
          fi
